### ISSUE TITLE
TypeError: 'AdaptiveAvgPool2d' object does not support indexing when using vgg and alexnet

### ISSUE THREAD

**Issue by texaspandaa** [anhquan0412/animation-classification#2]
Thanks for the nice feature, that's really helpful. However, when I try to apply it to vgg and alexnet learners, I got below error: 

/content/drive/My Drive/gradcam.py in get_grad_heatmap(learn, xb, y, size)
    150     xb = xb.cuda()
    151     m = learn.model.eval();
--> 152     target_layer = m[0][-1][-1] # last layer of group 0
    153     hook_a,hook_g = hooked_backward(m,xb,target_layer,y)
    154 

TypeError: 'AdaptiveAvgPool2d' object does not support indexing

any idea of how to fix it ? thanks in advance!

best regards,
fan

**Comment by anhquan0412** [comment]
Sorry for the delay. My code at the moment is dependent on Resnet structure, and vgg structure is vastly different but all you need to provide is a target layer so that the gradient can be calculated with respect to this layer. For vgg19 you can choose this layer in learn.model[0] aka the vgg body, e.g. learn.model[0][-1] is the last layer of the body (AdaptiveAvgPool2d) or learn.model[0][0][52] is the layer right before the AdaptiveAvgPool2d. In fact you have 53 layers to do some experiments on

To fix the error above you need to go into gradcam.py and manually edit the line at 152 by putting in the layer of your choice, e.g. target_layer = m[0][-1] or target_layer = m[0][0][52]. It works on my end so I bet it works on yours too.
